### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by drewstone** [Lightprotocol/light-protocol-program#2]
Running `cargo +1.59.0 test --release` and lots of tests fail. Any idea what could be the issue? Have you considered adding CI to this repo?

```
failures:
    compute_prepared_inputs_should_succeed
    deposit_should_succeed
    double_spend_should_not_succeed
    internal_transfer_should_succeed
    search_root_at_last_root_index_should_succeed
    signer_acc_not_in_first_place_should_not_succeed
    submit_proof_with_wrong_root_should_not_succeed
    submit_proof_with_wrong_signer_should_not_succeed
    withdrawal_should_succeed
```

Due to this error:
```
thread 'solana-bank-forks-client' panicked at 'Account data resizing not supported yet: 0 -> 4122. Consider making this test conditional on `#[cfg(feature = "test-bpf")]`', /Users/drew/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-program-test-1.9.5/src/lib.rs:341:17
thread 'search_root_at_last_root_index_should_succeed' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: Other, error: "the request exceeded its deadline" })', tests/onchain.rs:2580:10
```

**Comment by ananas-block** [comment]
try running it with solana cli version 1.8.16
